import streamlit as st


def render_action_plan_styles():
    st.markdown(
        """
        <style>
        .action-module{border-radius:28px !important;padding:26px !important;margin-top:18px !important;border:1px solid rgba(226,232,240,.95) !important;box-shadow:0 18px 48px rgba(15,23,42,.06) !important}
        .action-kicker{display:inline-flex !important;width:fit-content !important;padding:7px 12px !important;border-radius:999px !important;background:rgba(255,255,255,.72) !important;border:1px solid rgba(15,23,42,.08) !important;font-size:12px !important;font-weight:900 !important;color:#334155 !important;margin-bottom:12px !important;letter-spacing:.04em !important}
        .action-module h3{font-size:30px !important;line-height:1.2 !important;letter-spacing:-.04em !important;color:#0f172a !important;margin:0 0 10px !important}.action-module h4{color:#0f172a !important}.action-lead{font-size:15px !important;color:#475569 !important;line-height:1.85 !important;max-width:920px !important;margin:0 0 20px !important}.action-module p{color:#475569 !important;line-height:1.75 !important}
        .ldp-module{background:radial-gradient(circle at top left,#dbeafe,transparent 35%),linear-gradient(135deg,#ffffff,#eff6ff) !important}.pixel-module{background:radial-gradient(circle at top right,#dcfce7,transparent 34%),linear-gradient(135deg,#ffffff,#f0fdf4) !important}.ga4-module{background:radial-gradient(circle at top left,#ede9fe,transparent 34%),linear-gradient(135deg,#ffffff,#faf5ff) !important}.dropoff-module{background:radial-gradient(circle at top right,#fef3c7,transparent 34%),linear-gradient(135deg,#ffffff,#fffbeb) !important}.case-module{background:radial-gradient(circle at top left,#fce7f3,transparent 34%),linear-gradient(135deg,#ffffff,#fdf2f8) !important}.stability-module{background:radial-gradient(circle at top right,#dcfce7,transparent 34%),radial-gradient(circle at bottom left,#dbeafe,transparent 32%),linear-gradient(135deg,#ffffff,#f8fafc) !important}
        .action-flow-row{display:grid !important;grid-template-columns:1fr 44px 1fr 44px 1fr !important;gap:10px !important;align-items:stretch !important;margin:20px 0 !important}.action-flow-card{border-radius:20px !important;background:rgba(255,255,255,.78) !important;border:1px solid #dbeafe !important;padding:18px !important;min-height:110px !important;box-shadow:0 12px 30px rgba(15,23,42,.05) !important}.action-flow-card b{display:block !important;color:#0f172a !important;font-size:17px !important;margin-bottom:5px !important}.action-flow-card span{font-size:13px !important;color:#475569 !important;line-height:1.55 !important}.action-flow-arrow,.dropoff-arrow{display:flex !important;align-items:center !important;justify-content:center !important;color:#94a3b8 !important;font-size:28px !important;font-weight:950 !important}
        .action-grid-2{display:grid !important;grid-template-columns:repeat(2,minmax(0,1fr)) !important;gap:14px !important;margin-top:18px !important}.action-mini-card{border-radius:20px !important;background:rgba(255,255,255,.78) !important;border:1px solid #bbf7d0 !important;padding:18px !important;min-height:120px !important;box-shadow:0 12px 30px rgba(15,23,42,.05) !important}.action-mini-card b{color:#14532d !important;font-size:17px !important}.action-mini-card span{display:block !important;color:#475569 !important;font-size:13px !important;line-height:1.65 !important;margin-top:6px !important}
        .action-list{list-style:none !important;padding:0 !important;margin:18px 0 0 !important;display:grid !important;grid-template-columns:repeat(2,minmax(0,1fr)) !important;gap:12px !important}.action-list li{background:rgba(255,255,255,.78) !important;border:1px solid #ddd6fe !important;border-radius:18px !important;padding:14px 16px !important;color:#475569 !important;box-shadow:0 10px 26px rgba(15,23,42,.045) !important}.action-list li:before{content:'✓' !important;display:inline-flex !important;align-items:center !important;justify-content:center !important;width:22px !important;height:22px !important;border-radius:999px !important;background:#ede9fe !important;color:#6d28d9 !important;font-weight:950 !important;margin-right:8px !important}
        .dropoff-flow{display:grid !important;grid-template-columns:1fr 38px 1fr 38px 1.2fr 38px 1.2fr !important;gap:10px !important;align-items:stretch !important;margin-top:20px !important}.dropoff-node{border-radius:20px !important;background:rgba(255,255,255,.78) !important;border:1px solid #fde68a !important;padding:18px !important;color:#78350f !important;font-weight:850 !important;display:flex !important;align-items:center !important;justify-content:center !important;text-align:center !important;min-height:115px !important;box-shadow:0 12px 30px rgba(15,23,42,.05) !important}
        .timeline-card{display:grid !important;gap:12px !important;margin-top:20px !important}.timeline-card div{position:relative !important;border-radius:18px !important;background:rgba(255,255,255,.78) !important;border:1px solid #fbcfe8 !important;padding:15px 18px 15px 42px !important;color:#475569 !important;box-shadow:0 10px 26px rgba(15,23,42,.045) !important}.timeline-card div:before{content:'' !important;position:absolute !important;left:17px !important;top:20px !important;width:10px !important;height:10px !important;border-radius:999px !important;background:#ec4899 !important;box-shadow:0 0 0 5px #fce7f3 !important}.timeline-card b{color:#831843 !important}
        .stability-grid{display:grid !important;grid-template-columns:repeat(4,minmax(0,1fr)) !important;gap:12px !important;margin:20px 0 !important}.stability-box{background:rgba(255,255,255,.8) !important;border:1px solid #bbf7d0 !important;border-radius:18px !important;padding:16px !important;min-height:90px !important;display:flex !important;align-items:center !important;justify-content:center !important;text-align:center !important;color:#14532d !important;font-weight:850 !important;box-shadow:0 12px 30px rgba(15,23,42,.05) !important}.handover-card{background:linear-gradient(135deg,#ffffff,#eff6ff) !important;border:1px solid #bfdbfe !important;border-radius:22px !important;padding:20px !important;margin-top:16px !important;box-shadow:0 14px 34px rgba(15,23,42,.06) !important}.handover-card h4{font-size:20px !important;margin:0 0 8px !important;color:#0f172a !important}.handover-card p{font-size:14px !important;color:#475569 !important;line-height:1.8 !important;margin:0 !important}
        @media(max-width:900px){.action-flow-row,.dropoff-flow,.action-grid-2,.action-list,.stability-grid{grid-template-columns:1fr !important}.action-flow-arrow,.dropoff-arrow{min-height:24px !important;transform:rotate(90deg) !important}}
        </style>
        """,
        unsafe_allow_html=True,
    )
